[package]
name = "discord-mass-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = "0.12.2"
tokio = { version = "1.39.3", features = ["macros", "rt-multi-thread"] }
dotenvy = "0.15.7"
base64 = "0.22.1"
reqwest = "0.12.7"
